version: "3.8"
services:
  photo-gallery-server:
    image: zkimble/photo_gallery
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
      - 9181:9181
    volumes:
      - ~/photo_gallery/uploads:/photo_gallery/uploads
      - ~/photo_gallery/database:/photo_gallery/database
      - ~/photo_gallery/logs:/photo_gallery/logs
      - ~/photo_gallery/migrations/versions:/photo_gallery/migrations/versions
      - ~/photo_gallery/faces:/photo_gallery/app/static/faces
      - type: bind
        source: ${PHOTO_SOURCE_PATH}
        target: ${PHOTO_SOURCE_PATH}
        read_only: true
    init: true
    stdin_open: true
    tty: true
    shm_size: '1gb'
    environment:
      - UPLOAD_FOLDER=/photo_gallery/uploads