"""corrects photface name

Revision ID: 4542f0d1f226
Revises: 5395a9a87603
Create Date: 2020-11-01 13:40:05.228410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4542f0d1f226'
down_revision = '5395a9a87603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo_face', sa.Column('name_auto', sa.BOOLEAN(), nullable=True))
    op.drop_column('photo_face', 'name_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo_face', sa.Column('name_type', sa.BOOLEAN(), nullable=True))
    op.drop_column('photo_face', 'name_auto')
    # ### end Alembic commands ###
