"""adds created time to tasks

Revision ID: 5f6e45f2be72
Revises: fe6b089bacae
Create Date: 2021-04-24 11:06:18.267742

"""
from alembic import op
import sqlalchemy as sa
import app.models


# revision identifiers, used by Alembic.
revision = '5f6e45f2be72'
down_revision = 'fe6b089bacae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_task_date_created'), 'task', ['date_created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_date_created'), table_name='task')
    op.drop_column('task', 'date_created')
    # ### end Alembic commands ###
