"""adding search

Revision ID: 6e80d03c8610
Revises: a679943d6212
Create Date: 2021-01-16 21:32:14.883441

"""
from alembic import op
import sqlalchemy as sa
import app.models


# revision identifiers, used by Alembic.
revision = '6e80d03c8610'
down_revision = 'a679943d6212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_search',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('people', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_search')
    # ### end Alembic commands ###
