"""adds keywords to saved searches

Revision ID: 90002d808c79
Revises: 47371eaf17a7
Create Date: 2021-03-14 19:59:59.560716

"""
from alembic import op
import sqlalchemy as sa
import app.models


# revision identifiers, used by Alembic.
revision = '90002d808c79'
down_revision = '47371eaf17a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_search', sa.Column('keywords', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_search', 'keywords')
    # ### end Alembic commands ###
