"""PhotoFace table rename

Revision ID: 9e8472d07c56
Revises: dfea2067dfd8
Create Date: 2020-10-26 14:21:32.936575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e8472d07c56'
down_revision = 'dfea2067dfd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_face',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.Integer(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('bb_x1', sa.NUMERIC(), nullable=True),
    sa.Column('bb_y1', sa.NUMERIC(), nullable=True),
    sa.Column('bb_x2', sa.NUMERIC(), nullable=True),
    sa.Column('bb_y2', sa.NUMERIC(), nullable=True),
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location')
    )
    op.drop_table('photo_faces')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_faces',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('location', sa.INTEGER(), nullable=True),
    sa.Column('sequence', sa.INTEGER(), nullable=True),
    sa.Column('bb_x1', sa.NUMERIC(), nullable=True),
    sa.Column('bb_y1', sa.NUMERIC(), nullable=True),
    sa.Column('bb_x2', sa.NUMERIC(), nullable=True),
    sa.Column('bb_y2', sa.NUMERIC(), nullable=True),
    sa.Column('photo_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location')
    )
    op.drop_table('photo_face')
    # ### end Alembic commands ###
