"""initial schema

Revision ID: a679943d6212
Revises: 
Create Date: 2020-11-05 13:22:37.896624

"""
from alembic import op
import sqlalchemy as sa
import app.models


# revision identifiers, used by Alembic.
revision = 'a679943d6212'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_location'), 'photo', ['location'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.create_table('photo_face',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('bb_x1', sa.NUMERIC(), nullable=False),
    sa.Column('bb_y1', sa.NUMERIC(), nullable=False),
    sa.Column('bb_x2', sa.NUMERIC(), nullable=False),
    sa.Column('bb_y2', sa.NUMERIC(), nullable=False),
    sa.Column('bb_prob', sa.NUMERIC(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.Column('bb_auto', sa.BOOLEAN(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('name_auto', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location')
    )
    op.create_table('photo_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_metadata_key'), 'photo_metadata', ['key'], unique=False)
    op.create_index(op.f('ix_photo_metadata_value'), 'photo_metadata', ['value'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('progress', sa.NUMERIC(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_name'), 'task', ['name'], unique=False)
    op.create_table('face_embedding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('embedding', app.models.ArrayType(), nullable=True),
    sa.Column('photo_face_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['photo_face_id'], ['photo_face.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('photo_face_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('face_embedding')
    op.drop_index(op.f('ix_task_name'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_photo_metadata_value'), table_name='photo_metadata')
    op.drop_index(op.f('ix_photo_metadata_key'), table_name='photo_metadata')
    op.drop_table('photo_metadata')
    op.drop_table('photo_face')
    op.drop_table('followers')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_photo_location'), table_name='photo')
    op.drop_table('photo')
    # ### end Alembic commands ###
