"""empty message

Revision ID: cd877b65b0f3
Revises: 
Create Date: 2021-03-22 21:36:40.080071

"""
from alembic import op
import sqlalchemy as sa
import app.models


# revision identifiers, used by Alembic.
revision = 'cd877b65b0f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('face_detection_run', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_location'), 'photo', ['location'], unique=True)
    op.create_table('saved_search',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('people', sa.String(), nullable=True),
    sa.Column('keywords', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('photo_face',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('bb_x1', sa.NUMERIC(), nullable=False),
    sa.Column('bb_y1', sa.NUMERIC(), nullable=False),
    sa.Column('bb_x2', sa.NUMERIC(), nullable=False),
    sa.Column('bb_y2', sa.NUMERIC(), nullable=False),
    sa.Column('bb_prob', sa.NUMERIC(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.Column('bb_auto', sa.BOOLEAN(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('name_auto', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location')
    )
    op.create_table('photo_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_metadata_key'), 'photo_metadata', ['key'], unique=False)
    op.create_index(op.f('ix_photo_metadata_value'), 'photo_metadata', ['value'], unique=False)
    op.create_table('search_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_id', sa.Integer(), nullable=True),
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.Column('order_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photo.id'], ),
    sa.ForeignKeyConstraint(['search_id'], ['saved_search.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_results_order_by'), 'search_results', ['order_by'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('progress', sa.NUMERIC(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_name'), 'task', ['name'], unique=False)
    op.create_table('face_embedding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('embedding', app.models.ArrayType(), nullable=True),
    sa.Column('photo_face_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['photo_face_id'], ['photo_face.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('photo_face_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('face_embedding')
    op.drop_index(op.f('ix_task_name'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_search_results_order_by'), table_name='search_results')
    op.drop_table('search_results')
    op.drop_index(op.f('ix_photo_metadata_value'), table_name='photo_metadata')
    op.drop_index(op.f('ix_photo_metadata_key'), table_name='photo_metadata')
    op.drop_table('photo_metadata')
    op.drop_table('photo_face')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('saved_search')
    op.drop_index(op.f('ix_photo_location'), table_name='photo')
    op.drop_table('photo')
    # ### end Alembic commands ###
