"""PhotoFaces table

Revision ID: dfea2067dfd8
Revises: 0af4d8a21953
Create Date: 2020-10-26 14:13:16.246989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfea2067dfd8'
down_revision = '0af4d8a21953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_faces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.Integer(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('bb_x1', sa.NUMERIC(), nullable=True),
    sa.Column('bb_y1', sa.NUMERIC(), nullable=True),
    sa.Column('bb_x2', sa.NUMERIC(), nullable=True),
    sa.Column('bb_y2', sa.NUMERIC(), nullable=True),
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo_faces')
    # ### end Alembic commands ###
