"""adds task meta

Revision ID: fe6b089bacae
Revises: cd877b65b0f3
Create Date: 2021-04-17 19:33:30.492922

"""
from alembic import op
import sqlalchemy as sa
import app.models


# revision identifiers, used by Alembic.
revision = 'fe6b089bacae'
down_revision = 'cd877b65b0f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('meta', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'meta')
    # ### end Alembic commands ###
